// Generated by Selenium IDE

using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
using Autotests.Models.Task;
using NUnit.Framework;

namespace Autotests.Tests.Task
{
    [TestFixture]
    public class TaskTest : BaseTest
    {
        [Test]
        public void Create()
        {
            ApplicationManager.AuthenticationHelper.AuthenticateAndWait();
            ApplicationManager.TaskHelper.AddItem(ApplicationManager.CreateData);
        }
        
        [Test]
        public void Edit()
        {
            ApplicationManager.AuthenticationHelper.AuthenticateAndWait();
            ApplicationManager.TaskHelper.EditItem(ApplicationManager.EditData);
        }
        
        [Test]
        public void Delete()
        {
            ApplicationManager.AuthenticationHelper.AuthenticateAndWait();
            ApplicationManager.TaskHelper.DeleteItem(ApplicationManager.DeleteData);
        }
        
        public static IEnumerable<TaskData> GroupDataFromXmlFile()
        {
            return (List<TaskData>) new XmlSerializer(typeof(List<TaskData>))
                .Deserialize(new StreamReader(ApplicationManager.XmlDataPath));
        }


        [Test, TestCaseSource(nameof(GroupDataFromXmlFile))]
        public void CreateFromXml(TaskData taskData)
        {
            ApplicationManager.AuthenticationHelper.AuthenticateAndWait();
            ApplicationManager.TaskHelper.AddItem(new CreateData(taskData));
        }
    }
}